config/routes.rb
Rails.application.routes.draw do
  # ----------------------------------------------
  #                   FRONT
  # ----------------------------------------------

  root 'home#index'

  devise_for :users, controllers: { omniauth_callbacks: 'auth_callbacks' }

  match '/help',  to: 'home#help',  via: 'get'
  match '/about', to: 'home#about', via: 'get'

  resources :posts do
    resources :comments, only: %i(create destroy)
    put :vote_up, :vote_down, on: :member

    resources :comments, only: %i(create destroy) do
    end
  end

  # ----------------------------------------------
  #                   ADMIN
  # ----------------------------------------------
  namespace :admin do
    get '/', to: 'dashboard#index'
    # Categories
    resources :categories, except: %i(show)
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  acts_as_nested_set

  validates :name, presence: true
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < Admin::ApplicationController
    respond_to :html, :json

    helper_method :categories, :category

    def index
      @q = Category.order(name: :asc).ransack(params[:q])
    end

    def new
      @category = Category.new
    end

    def create
      @category = Category.new(category_params)
      @category.save ? flash[:success] = t(:success_she, obj: t(:category), name: @category.name, act: t(:created_she)) : flash[:error] = t(:error)
      respond_with @category, location: admin_categories_url
    end

    def update
      category.update(category_params)
      category.save ? flash[:success] = t(:success_she, obj: t(:category), name: category.name, act: t(:updated_she)) : flash[:error] = t(:error)
      respond_with category, location: admin_categories_url
    end

    def destroy
      category.destroy
      category.destroyed? ? flash[:warning] = t(:success_she, obj: t(:category), name: category.name, act: t(:destroyed_she)) : flash[:error] = t(:error)
      redirect_to admin_categories_url
    end

    private

    def categories
      @categories = @q.result(distinct: true)
    end

    def category
      @category ||= Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :description, :parent_id)
    end
  end
end

app/views/admin/categories/_form.slim
  = simple_form_for category, url: [:admin, category] do |f|
    .field = f.input  :name, label: t(:name)
    .field
      = f.label  :parent_id, label: t(:parent)
      = f.select :parent_id, nested_set_options(Category, category) {|i| "#{'-' * i.level} #{i.name}" }, include_blank: '---'
    .field = f.input  :description, label: t(:description), input_html: { rows: 5 }
    .buttons = f.submit t(:save_category), class:'button success'
    = link_to fa_icon('arrow-left', text: t(:back)), admin_categories_path

app/views/admin/categories/_search.slim
.search-panel
  .row
    = search_form_for @q, url: admin_categories_path do |f|
      .large-4.columns
        = f.label :name_cont, t(:name)
        = f.search_field :name_cont
      .large-4.columns
        = f.label :parent_name_cont, t(:parent)
        = f.search_field :parent_name_cont
      .large-4.columns
        = f.submit t(:seach), class:'button small'

app/views/admin/categories/edit.slim
- content_for :page_title, t(:edit_category)
- content_for :page_header, t(:edit_category)

== render 'form'

app/views/admin/categories/index.slim
- content_for :page_title, t(:categories)
- content_for :page_header, t(:categories)

= link_to fa_icon(:plus, text: t(:add_category)), new_admin_category_path, class:'button success'

== render 'search'

table.full-width
  thead
    tr
      th.name        = t(:name)
      th.parent      = t(:parent)
      th.description = t(:description)
      th.actions     = t(:actions)
  tbody
    - categories.each do |category|
      tr
        td.name        = category.name
        td.parent      = category.parent.present? ? category.parent.name : ""
        td.description = truncate(category.description, length: 40)
        td.actions
          = link_to fa_icon(:pencil), edit_admin_category_path(category)
          = link_to fa_icon(:trash), [:admin, category], data: {confirm: t('are_you_sure?')}, method: :delete

app/views/admin/categories/new.slim
- content_for :page_title, t(:edit_category)
- content_for :page_header, t(:edit_category)

== render 'form'