config/routes.rb
Rails.application.routes.draw do
  # ----------------------------------------------
  #                   FRONT
  # ----------------------------------------------

  root 'home#index'

  devise_for :users, controllers: { omniauth_callbacks: 'auth_callbacks' }

  match '/help',  to: 'home#help',  via: 'get'
  match '/about', to: 'home#about', via: 'get'

  resources :posts do
    resources :comments, only: %i(create destroy)
    put :vote_up, :vote_down, on: :member

    resources :comments, only: %i(create destroy) do
    end
  end

  # ----------------------------------------------
  #                   ADMIN
  # ----------------------------------------------
  namespace :admin do
    get '/', to: 'dashboard#index'
    # Categories
    resources :categories, except: %i(show)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  acts_as_commentable
  acts_as_votable

  belongs_to :author, class_name: 'User', foreign_key: "author_id"
  belongs_to :category

  validates :title, :description, :category, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :html, :json

  helper_method :posts, :post, :comment, :categories

  def index
    respond_with posts
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.save ? flash[:success] = t(:success_it, obj: t(:post), name: @post.title, act: t(:created_it)) : flash[:error] = t(:error)
    respond_with @post
  end

  def update
    post.update(post_params)
    post.save ? flash[:success] = t(:success_it, obj: t(:post), name: post.title, act: t(:updated_it)) : flash[:error] = t(:error)
    respond_with post
  end

  def destroy
    post.destroy
    post.destroyed? ? flash[:warning] = t(:success_it, obj: t(:post), name: post.title, act: t(:destroyed_it)) : flash[:error] = t(:error)
    redirect_to posts_path
  end

  def vote_up
    post.liked_by current_user

    respond_with(post)
  end

  def vote_down
    post.disliked_by current_user

    respond_with(post)
  end

  private

  def post
    @post ||= Post.friendly.find(params[:id])
  end

  def posts
    if params[:category].present?
      @posts ||= Post.where(category_id: params[:category]).order(created_at: :desc)
    else
      @posts ||= Post.all.order(created_at: :desc)
    end
  end

  def comment
    @comment ||= post.comments.build
  end

  def categories
    @categories ||= Category.all.order(name: :asc)
  end

  def post_params
    params.require(:post).permit(:title, :description, :author_id, :post_id, :category_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def last_comment_info(post)
    " (#{time_ago_in_words(post.comments.last.created_at)} #{t(:ago)})" if post.comments.size > 0
  end

  def votes_up_info(post)
    "#{t(:vote_up)} - #{post.votes_for.up.count}".html_safe
  end

  def votes_down_info(post)
    "#{t(:vote_down)} - #{post.votes_for.down.count}".html_safe
  end

  def timestamp_display(time)
    time.strftime('%y %b %d - %H:%M') if time
  end
end

app/views/posts/_comments.slim
#comments.column.large-8.medium-8
  h3
    = t(:comments)
    = " (#{post.comments.recent.size})"

  .comments-collection == render 'comments/collection'
  .comments-form       == render 'comments/form'

app/views/posts/_form.html.slim
= simple_form_for(post) do |f|

  .form-inputs
    = f.input :title,       label: t(:title)
    = f.input :description, label: t(:description), as: :text, input_html: { rows: 8}
    = f.label :category_id, label: t(:category)
    = f.select :category_id, nested_set_options(Category, @category) {|i| "#{'-' * i.level} #{i.name}" }, include_blank: '---'

  .form-actions
    .buttons = f.submit t(:save_post), class:'button success'

= link_to fa_icon('arrow-left', text: t(:back)), posts_path

app/views/posts/_single.slim
.column.align-middle.post
  .post-header = link_to post.title, post
  .post-body   = post.description.html_safe
  .post-footer.row
    .post-author.column.medium-3
      = fa_icon(:user)
      = post.author.full_name if post.author

    .post-timestamp.column.medium-3
      = fa_icon(:calendar)
      = timestamp_display(post.created_at)

    .post-category.column.medium-2
      = link_to fa_icon('list-alt')+post.category.name, posts_path(category: post.category_id), class: 'simple' if post.category

    .post-votes.column.medium-3
      - if current_user.voted_for? post
        span         = fa_icon('pie-chart')
        span.r-space = votes_up_info(post)
        span         = votes_down_info(post)
      - else
        span = link_to fa_icon('hand-paper-o')+t(:vote_up)+'!', vote_up_post_path(post), method: :put, class: 'simple r-space'
        span = link_to fa_icon('close')+t(:vote_down)+'!',      vote_down_post_path(post), method: :put, class: 'simple'

    .post-comments.column.medium-1
      = fa_icon(:comments)
      = post.comments.size if post.comments
      /= last_comment_info(post)

/    - if post.author == current_user || current_user.admin?
/      .post-actions.column.medium-2.text-center
/        = link_to fa_icon(:pencil), edit_post_path(post)
/        = link_to fa_icon(:trash),  post, data: { confirm: t(:are_you_sure?)}, method: :delete

app/views/posts/edit.html.slim
- content_for :page_title, t(:edit_post)
- content_for :page_header, t(:edit_post)

== render 'form'

app/views/posts/index.html.slim
- content_for :page_title,  t(:posts)
- content_for :page_header, t(:posts)

.column.large-3
  #sidebar
    .block
      = link_to fa_icon(:plus, text: t(:add_post)), new_post_path, class:'button success'

    .block
      .block-title = t :filter_by_categories
      .block-body
        ul.categories
          li = link_to t(:all), posts_path, class: 'simple'
          - categories.each do |c|
            li = link_to c.name, posts_path(category: c.id), class: 'simple'

.column.large-9
  #posts
    - if @posts.present?
      - @posts.each do |post|
        == render 'posts/single', post: post
    - else
      p.t-space2x = t(:no_posts)

app/views/posts/new.html.slim
- content_for :page_title, t(:add_post)
- content_for :page_header, t(:add_post)

== render 'form'

app/views/posts/show.html.slim
- content_for :page_title,  t(:post)
- content_for :page_header, t(:post)

#posts
  == render 'posts/single', post: post

== render 'comments'