config/routes.rb
Rails.application.routes.draw do
  # ----------------------------------------------
  #                   FRONT
  # ----------------------------------------------

  root 'home#index'

  devise_for :users, controllers: { omniauth_callbacks: 'auth_callbacks' }

  match '/help',  to: 'home#help',  via: 'get'
  match '/about', to: 'home#about', via: 'get'

  resources :posts do
    resources :comments, only: %i(create destroy)
    put :vote_up, :vote_down, on: :member

    resources :comments, only: %i(create destroy) do
    end
  end

  # ----------------------------------------------
  #                   ADMIN
  # ----------------------------------------------
  namespace :admin do
    get '/', to: 'dashboard#index'
    # Categories
    resources :categories, except: %i(show)
  end
end

app/views/layouts/_head.slim
meta charset="utf-8"

title = page_title

= stylesheet_link_tag '//fonts.googleapis.com/css?family=PT+Sans:400,700italic,700,400italic|PT+Sans+Caption:400,700&subset=latin,cyrillic', 'application', media: 'all', 'data-turbolinks-track' => true
= javascript_include_tag 'application'

= csrf_meta_tags

= yield :head

app/views/layouts/_header.slim
.icon-bar.five-up
  a.item href="#{root_path}"
    label = t(:home)
  a.item href="#{posts_path}"
    label = t(:posts)
  a.item href="#{about_path}"
    label = t(:about)
  a.item href="#{help_path}"
    label = t(:help)
  a.item href="#{admin_path}"
    label = t(:admin)

app/views/layouts/application.html.erb
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "GearX" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <script>
      window.fbAsyncInit = function() {
          FB.init({
              appId      : '691939290943279',
              xfbml      : true,
              version    : 'v2.5'
          });
      };

      (function(d, s, id){
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) {return;}
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_US/sdk.js";
          fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
    </script>

    <header id="header">
      <%= render 'layouts/header' %>
    </header>

    <main id="main" class="row">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>

    </main>

    <footer id="footer">
      <%= render 'layouts/footer' %>
    </footer>

  </body>
</html>

app/views/layouts/application.slim
doctype html
html
  head
    = render 'admin/layouts/head'

    body id="page--#{controller.controller_name}-#{controller.action_name}"
      = render 'layouts/header'

      main#main-content role="main" class="row"

        #content
          - if content_for?(:page_header)
            h2.page-header = yield :page_header

          = yield